<a href="https://colab.research.google.com/github/hyesungKomet/deep_learning/blob/main/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[2,9], [1,5], [3,6]], dtype=float)
y = np.array([[92], [86], [89]], dtype=float)

#스케일링(정규화)
X = X/np.amax(X, axis=0)
y = y/100
print(X)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [ ]:
class NeuralNetwork(object):
  def __init__(self):
    #파라미터들
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3

    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) #2X3
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) #3X1

  def Forward(self, X):#정방향
    self.z = np.dot(X, self.W1)
    self.z2 = self.sigmoid(self.z) #활성화함수로 시그모이드
    self.z3 = np.dot(self.z2, self.W2)
    output = self.sigmoid(self.z3)
    return output

  def sigmoid(self, s, deriv=False):
    if(deriv == True): #오차역전파일 때
      return s*(1-s)
    return 1/(1+np.exp(-s))#너무 큰 값 나오지 않도록 조정한 시그모이드

  def backward(self, X, y, output):
    self.output_error = y - output#output부터 거꾸로!
    self.output_delta = self.output_error * self.sigmoid(output, deriv=True)

    self.z2_error = self.output_delta.dot(self.W2.T)#전치행렬 - 행과 열을 바꾼다!
    self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True)

    self.W1 += X.T.dot(self.z2_delta)
    self.W2 += self.z2.T.dot(self.output_delta)

  def train(self, X, y):
    output = self.Forward(X)
    self.backward(X, y, output)


In [ ]:
NN = NeuralNetwork()

In [ ]:
for i in range(1000):
    if(i%100==0):#매 100회마다 출력
      print("Number: ", i)
      print("W1: ", NN.W1)
      print("W2: ", NN.W2)
      print("output: ", NN.Forward(X))
      print("Loss: ", np.mean(np.square(y - NN.Forward(X))))#손실함수 - 오차제곱합
      print()
    NN.train(X, y)

print("Input: ", X)
print("ActualOutput: ", y)
print("Loss: ", np.mean(np.square(y - NN.Forward(X))))
print()
print("Predicted Output: ", NN.Forward(X))

Number:  0
W1:  [[ 0.37334594  0.91811317  0.58094961]
 [ 0.18670564 -0.25993013  0.86157878]]
W2:  [[-0.23459017]
 [ 0.91657023]
 [ 0.13488612]]
output:  [[0.62258341]
 [0.61157072]
 [0.64064324]]
Loss:  0.07078417438992611

Number:  100
W1:  [[0.38421901 1.11718628 0.64371879]
 [0.20949727 0.01218291 0.95199516]]
W2:  [[0.43719502]
 [1.62075602]
 [0.9817853 ]]
output:  [[0.89627014]
 [0.86678051]
 [0.90603328]]
Loss:  0.0002887158799756326

Number:  200
W1:  [[0.38186339 1.11502429 0.63702269]
 [0.2172313  0.04149027 0.96033154]]
W2:  [[0.43500799]
 [1.61264903]
 [0.98804504]]
output:  [[0.89711371]
 [0.86737307]
 [0.90625912]]
Loss:  0.00028083445394392215

Number:  300
W1:  [[0.37933119 1.11204744 0.6299434 ]
 [0.22446661 0.06873754 0.96797617]]
W2:  [[0.43057028]
 [1.60248921]
 [0.99132523]]
output:  [[0.8973544 ]
 [0.86735598]
 [0.90595386]]
Loss:  0.00027381977559905033

Number:  400
W1:  [[0.37687246 1.10906769 0.62290135]
 [0.23151195 0.09500788 0.97545192]]
W2:  [[0.42621053]