<a href="https://colab.research.google.com/github/hyesungKomet/deep_learning/blob/main/ch_4_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 오차제곱합

In [ ]:
def sum_squares_error(y, t):
  return 0.5 * np.sum((y-t)**2)

# 교차 엔트로피 오차

In [ ]:
def cross_entropy_error(y, t):
  delta = 1e-7
  return np.sum(t*np.log(y+delta))

# 배치용 교차 엔트로피 오차

In [ ]:
def cross_entropy_error(y, t):
  if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, y.size)

  batch_size = y.shape[0]
  return -np.sum(t*np.log(y+1e-7)) / batch_size

# 기울기

In [ ]:
def numerical_gradient(f, x):
  h = 1e-4
  grad = np.zeros_like(x) #x와 형상 같고 0 들어간 배열

  for idx in range(x.size):
    tmp_val = x[idx]
    x[idx] = tmp_val + h
    fxh1 = f(x)

    x[idx] = tmp_val - h
    fxh2 = f(x)

    grad[idx] = (fxh1 - fxh2) / (2*h)
    x[idx] = tmp_val

  return grad

In [ ]:
def function(x):
  return x[0]**2 + x[1]**2

numerical_gradient(function, np.array([3.0, -4.0]))

array([ 6., -8.])

# 경사하강법

In [ ]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
  x = init_x

  for i in range(step_num):
    grad = numerical_gradient(f, x)
    x -= lr * grad
  return x

In [ ]:
def function(x):
  return x[0]**2 + x[1]**2

x= np.array([3.0, -6.0])
gradient_descent(function, x, lr=0.1)

array([ 6.11110793e-10, -1.22222159e-09])

In [ ]:
#learning rate 높은 경우
x= np.array([3.0, -5.0])
gradient_descent(function, x, lr = 10)

array([2.58459459e+13, 1.80220317e+12])

In [ ]:
#learning rate 낮은 경우
x= np.array([3.0, -5.0])
gradient_descent(function, x, lr=0.0001)

array([ 2.94059014, -4.90098356])

In [ ]:
import sys, os
sys.path.append(os.pardir)
import numpy as np

In [ ]:
def softmax(x):
  c = np.max(x)
  exp_x = np.exp(x - c)
  sum_exp_x = np.sum(exp_x)
  y = exp_x / sum_exp_x
  return y

In [ ]:
class simpleNet:
  def __init__(self):
    self.W = np.random.randn(2,3) #정규분포에서의 난수 생성

  def predict(self, x):
    return np.dot(x, self.W) # W*x

  def loss(self, x, t):
    z = self.predict(x)
    y = softmax(z)
    loss = cross_entropy_error(y, t)
    return loss

In [ ]:
net = simpleNet()
x = np.array([0.6, 0.9])

print("가중치: \n", net.W)
p = net.predict(x)
print("x*W: ", p)
print(np.argmax(p))
t = np.array([0,0,1])
net.loss(x, t)


가중치: 
 [[-0.74913594  0.55967376 -0.21354801]
 [ 1.7853604   0.299224   -0.58715308]]
x*W:  [ 1.1573428   0.60510586 -0.65656658]
0


2.3670323603288193

# 다차원 배열을 처리할 수 있는 numerical_gradient 함수

In [ ]:
def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 値を元に戻す
        it.iternext()   
        
    return grad

In [ ]:
def f(W):
  return net.loss(x, t)
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.34508975  0.19865459 -0.54374435]
 [ 0.51763463  0.29798189 -0.81561652]]
